export const ActionType = {
  GET_PRODUCT_LIST_REQUESTED: "GET_PRODUCT_LIST_REQUESTED",
  GET_PRODUCT_LIST_SUCCESS: "GET_PRODUCT_LIST_SUCCESS",
  GET_PRODUCT_LIST_FAILED: "GET_PRODUCT_LIST_FAILED",
  GET_PRODUCT_DETAILS_REQUESTED: "GET_PRODUCT_DETAILS_REQUESTED",
  GET_PRODUCT_DETAILS_SUCCESS: "GET_PRODUCT_DETAILS_SUCCESS",
  GET_PRODUCT_DETAILS_FAILED: "GET_PRODUCT_DETAILS_FAILED",
};
